run CS program. safeexec not enabled yet

diff --git a/doc/problemexamples/problemtemplate/run/cs b/doc/problemexamples/problemtemplate/run/cs
--- a/doc/problemexamples/problemtemplate/run/cs
+++ b/doc/problemexamples/problemtemplate/run/cs
@@ -107,17 +107,17 @@ if [ "$6" != "" ]; then
 fi
 
 cp "$2" stdin0 2>/dev/null
-cp "$1" run 2>/dev/null
+cp -r "$1" run 2>/dev/null
 
-file run.dll | grep -iq "statically linked"
-if [ "$?" != "0" ]; then
-  echo "Aborting because $1 is not statically linked"
-  exit 47
-fi
+#file run.dll | grep -iq "statically linked"
+#if [ "$?" != "0" ]; then
+#  echo "Aborting because $1 is not statically linked"
+#  exit 47
+#fi
 
 cdir=`pwd`
 echo "Current directory is $cdir -- chrooting on it" >&2
-./$1/ConsoleApp < stdin0 #$sf -F10 -f$maxf -r$nruns -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 "./ConsoleApp/run.dll"
+./runexe/ConsoleApp < stdin0 #$sf -F10 -f$maxf -r$nruns -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 "./ConsoleApp/run.dll"
 ret=$?
 if [ $ret -gt 10 ]; then
 	ret=0
